### ISSUE TITLE
Disparar evento cuando un personaje es golpeado por otro.

### ISSUE THREAD

**Issue by nlareu** [nlareu/DashWar#22]
El evento debe pertenecer a la clase avatar controller

**Comment by ColoLP** [comment]
Entendi medianamente como funciona, aparentemente usaste un sistema paralelo de collisiones para cada una de las collisiones. Posiblemente sea algun patron puntual de diseño me gustaria saber cual es, asi lo estudio un poco mas en profundidad. 

En el AvatarAvatarCollision.cs deje un "Debug.Log" para mostrar que encontre donde me muestra contra quien choco.

**Comment by nlareu** [comment]
No se está disparando el evento solicitado. Solo se agregó log. Hablar por wahtsap para conversar sobre el ticekt y explicarlo mejor.

**Comment by nlareu** [comment]
Cerrado ya uqe esto no se va a ser ahora. En el futuro abrir otro ticket si es necesario.
