### ISSUE TITLE
Reproducir música de fondo en pantallas de menues.

### ISSUE THREAD

**Issue by nlareu** [nlareu/DashWar#40]
- Debe reproducirse en loop. O sea que cuando termine que vuelva a empezar.
- No debe cortarse ni reiniciarse cuando se cambia de pantalla de menú a otra pantalla de menú.
- No debe cortarse con otros efectos de sonido (como por ejemplo el efecto de sonido de apretar un botón de menú, al seleccionar un personaje, etc).
- Sí debe cortarse en los niveles donde se juega (ya que los niveles tendrán otra música).

**Comment by Daniel-ECB** [comment]
Ya hecho, la pantalla principal reproduce un tema de título y los menúes reproducen otro, todo según las especificaciones. Las pistas que coloqué son temporales esperando cambiarlas por unas hechas específicamente para este juego.
