### ISSUE TITLE
Digitalizar y pintar los bocetos de los jugadores

### ISSUE THREAD

**Issue by nlareu** [nlareu/DashWar#43]
- Diujarlos de cuerpo completo y en 360: de frente, de perfil ,de 1/4 perfil y espaldas.

**Comment by GianlucaMascaro** [comment]
![ny sheet](https://user-images.githubusercontent.com/46942807/51872070-fb219900-2336-11e9-8ca6-388b038b93c2.png)
Este es el primer sheet. Antes de continuar quiero consultarle que en mi opinión, no hay uso en una vista en 3/4 de espalda. Para el juego 2D que estamos haciendo, el único uso que tendría es para crear modelos 3D, o para un artbook.

**Comment by nlareu** [comment]
- Me gusta mucho como quedó. Sugiero algunos cambios para probar. En el boceto me lo imaginaba con el pelo gris y además se veía más malicioso (los ojos y la expresión facial). Me gustaba esa onda. Probemosla por favor.

- En lo referido al 3/4 de espalda, si vos pensas que no tiene sentido entonces no la hagamos.

**Comment by GianlucaMascaro** [comment]
![ny sheet revised](https://user-images.githubusercontent.com/46942807/52091723-2c4ad500-2594-11e9-9106-0646cc9db477.png)
Cambios aplicados, el pelo gris con un gradiente blanco y una expresión más maliciosa.

Además, ahora tenemos el sheet de la jugadora de China - Liena Ying.
![china sheet](https://user-images.githubusercontent.com/46942807/52091785-5ef4cd80-2594-11e9-812e-8a2056ff2013.png)

**Comment by GianlucaMascaro** [comment]
![brazilian sheet](https://user-images.githubusercontent.com/46942807/52232654-d7f96b00-289b-11e9-927d-5c1a377f39fc.png)
Y ahora el personaje de Brasil - Gabriel Dangelo.

**Comment by GianlucaMascaro** [comment]
![russian sheet](https://user-images.githubusercontent.com/46942807/52430141-344ecb80-2ae4-11e9-9e6f-eb8d4a64a7ee.png)
Personaje Ruso, Sasha Mikhail.

**Comment by GianlucaMascaro** [comment]
![a r g e n t i n a sheet](https://user-images.githubusercontent.com/46942807/52539439-d973d900-2d5c-11e9-8e38-bf394ac8a0d4.png)
Finalmente, nuestro jugador Argentino: Leo Rossi.
