### ISSUE TITLE
Avatar no salta si esta por encima de otro objeto que no tenga tag "Ground".

### ISSUE THREAD

**Issue by nlareu** [nlareu/DashWar#44]
Modificar cómo se chequea que el avatar esté tocando el piso. Hacer este chequeo utilizando otro objeto en la parte inferion del avatar y chequeando si este "ground checker" está en colision con objetos.

**Comment by Daniel-ECB** [comment]
Resuelto el bug, igualmente siempre hay que especificar sobre que objetos puede o no saltar el jugador, ver commit del día 20022019
